;gaist-ultra-V7_1, AI_Icy_Bay, Henrik_Nielsen
[Files]
ShortName=Icy Bay
PathnameHull=Resources/Ships/icy_bay/icy_bay_hull.obj
PathnameFull=Resources/Ships/icy_bay/icy_bay.gltf
PathnamePropeller1=Resources/Ships/icy_bay/icy_bay_propeller.gltf
PathnamePropeller2=
PathnameRudder=Resources/Ships/icy_bay/icy_bay_rudder.gltf
PathnameRadar1=Resources/Ships/icy_bay/icy_bay_radar1.gltf
PathnameRadar2=Resources/Ships/icy_bay/icy_bay_radar2.gltf
PathnameFlag=Resources/Ships/icy_bay/Flag_of_Alaska.png
ThrustSound=Resources/Sounds/Engine16.wav
BowThrusterSound=
SternThrusterSound=
[Views]
ViewWheel=11.5 7.7 0
ViewLeft=9.4 7.7 -4
ViewRight=9.4 7.7 4
ViewBow=18.575 5.65 0
ViewStern=-17.608 3.1 0
[Dimensions]
Class=5
Length=40
SpeedMaxKt=12.6
SpeedEcoKt=11.5
Mass_t=600
PosGravity=0.8 -0.5 0
PitchRollFactor=0.3
EnvMapFactor=0
ContourType=1
AreaWetted=426.77
LWL=37.52
PositionY=0.16
AreaFront=55.7391
AreaFrontCenter=0 3.3075 2.3868
AreaLat=167.8179
AreaLatCenter=4.0600 3.0500 0
[Power]
PosPower=-17 -20 0
PowerkW=1200
PowerStepMax=20
[Propellers]
PropRpmMax=350
PropRpmIncrement=70
nPropeller=1
PosPropeller1=-16.512 -2 0
PropTorque1=-1
PosPropeller2=0 0 0
PropTorque2=1
PropDiameter=1.73
WakeWidth=0.8
[Rudder]
PosRudder=-18.8 -1.63 0
RudderIncrement=1
RudderStepMax=35
RudderRotSpeed=5
nRudder=1
PosRudder1=-18.539 -0.3655 0
PosRudder2=0 0 0
[Turning]
TurnabilityAtSpeed=0.4
RoTMax=230
PivotFwd=0.2
PivotBwd=0.7
CentrifugalPerf=3
[Spray]
SprayVerticalPerf=5
SprayMultiplier=10
SprayLength=0.15
SprayType=0
[Chimneys]
nChimney=2
PosChimney1=5.8022 9.1038 -2.9
PosChimney2=5.8022 9.1038 2.9
[BowThruster]
HasBowThruster=0
PosBowThruster=0 0 0
BowThrusterPerf=0
BowThrusterPowerW=0
BowThrusterStepMax=0
BowThrusterRpmMin=0
BowThrusterRpmMax=500
BowThrusterRpmIncrement=0
[SternThruster]
HasSternThruster=0
PosSternThruster=0 0 0
SternThrusterPerf=0
SternThrusterPowerW=0
SternThrusterStepMax=0
SternThrusterRpmMin=0
SternThrusterRpmMax=0
SternThrusterRpmIncrement=0
[Autopilot]
BaseP=2
BaseI=1
BaseD=30
MaxIntegral=2
[Lights]
LightPositions=9.9544 9.105 -2.2045,9.9544 9.105 2.2045,-19.812 3.0976 0,9.877 14.105 0
LightColors=1 0 0,0 1 0,1 1 1,1 1 1
[Radar]
nRadar=2
PosRadar1=11.5 10.23 1.5
RotationRadar1=20
PosRadar2=11.5 9.53 -1.5
RotationRadar2=30
[Waves]
CenterFore=20
BaseFroude=10
[Flag]
bFlag=1
PosFlag=9.1591 12.92 1.0124
DimXFlag=1
