;gaist-ultra-V7_1, AI_UT745_Malaviya, Henrik_Nielsen
[Files]
ShortName=Bourbon Hidra
PathnameHull=Resources/Ships/bourbon_hidra/bourbon_hidra_hull.obj
PathnameFull=Resources/Ships/bourbon_hidra/bourbon_hidra.gltf
PathnamePropeller1=Resources/Ships/bourbon_hidra/bourbon_hidra_propeller1.gltf
PathnamePropeller2=Resources/Ships/bourbon_hidra/bourbon_hidra_propeller2.gltf
PathnameRudder=Resources/Ships/bourbon_hidra/bourbon_hidra_rudder.gltf
PathnameRadar1=Resources/Ships/bourbon_hidra/bourbon_hidra_radar1.gltf
PathnameRadar2=Resources/Ships/bourbon_hidra/bourbon_hidra_radar2.gltf
PathnameFlag=Resources/Ships/bourbon_hidra/Flag_of_Saint_Vincent_and_the_Grenadines.png
ThrustSound=Resources/Sounds/Engine16.wav
BowThrusterSound=Resources/Sounds/Engine0.wav
SternThrusterSound=Resources/Sounds/Engine0.wav
[Views]
ViewWheel=24.924 14.1 0
ViewLeft=29.1 14.1 -5
ViewRight=29.1 14.1 5
ViewBow=31.443 9.2 0
ViewStern=15.897 6.7 6.66108
[Dimensions]
Class=5
Length=83.97
SpeedMaxKt=16.8
SpeedEcoKt=15.6
Mass_t=5700
PosGravity=0 -1.5 0
PitchRollFactor=0.25
EnvMapFactor=0
ContourType=1
AreaWetted=1922.60
LWL=79.12
PositionY=-0.26
AreaFront=207.8798
AreaFrontCenter=0 6.4669 4.0139
AreaLat=683.5803
AreaLatCenter=4.6479 5.1994 0
[Power]
PosPower=-38 -2.6395 0
PowerkW=11600
PowerStepMax=20
[Propellers]
PropRpmMax=200
PropRpmIncrement=6.5
nPropeller=2
PosPropeller1=-37.199 -2.6395 -5
PropTorque1=-1
PosPropeller2=-37.199 -2.6395 5
PropTorque2=1
PropDiameter=2.86
WakeWidth=0.8
[Rudder]
PosRudder=-40.493 -2.84 0
RudderIncrement=1
RudderStepMax=35
RudderRotSpeed=5
nRudder=2
PosRudder1=-39.541 -0.8 -5
PosRudder2=-39.541 -0.8 5
[Turning]
TurnabilityAtSpeed=0.25
RoTMax=230
PivotFwd=0.2
PivotBwd=0.7
CentrifugalPerf=3
[Spray]
SprayVerticalPerf=5
SprayMultiplier=10
SprayLength=0.15
SprayType=0
[Chimneys]
nChimney=2
PosChimney1=19.152 19.268 -5.9477
PosChimney2=19.152 19.268 5.9477
[BowThruster]
HasBowThruster=1
PosBowThruster=28.476 -3.5 0
BowThrusterPerf=64
BowThrusterPowerW=10000
BowThrusterStepMax=5
BowThrusterRpmMin=0
BowThrusterRpmMax=500
BowThrusterRpmIncrement=100
[SternThruster]
HasSternThruster=1
PosSternThruster=-34.1 -2.64 0
SternThrusterPerf=64
SternThrusterPowerW=10000
SternThrusterStepMax=5
SternThrusterRpmMin=0
SternThrusterRpmMax=500
SternThrusterRpmIncrement=100
[Autopilot]
BaseP=2
BaseI=1
BaseD=30
MaxIntegral=2
[Lights]
LightPositions=19.7 12.976 -6.9767,19.7 12.976 6.9767,-43.9 4.3 0,19.3 23.5 0,40.067 8.7 0
LightColors=1 0 0,0 1 0,1 1 1,1 1 1,1 1 1
[Radar]
nRadar=2
PosRadar1=20.391 21.67 0
RotationRadar1=20
PosRadar2=21.625 19.487 0
RotationRadar2=30
[Waves]
CenterFore=80
BaseFroude=10
[Flag]
bFlag=1
PosFlag=17.943 23.673 1.0124
DimXFlag=1
