;gaist-ultra-V7_1, AI_Osterbotten, Henrik_Nielsen
[Files]
ShortName=Cargo Osterbotten
PathnameHull=Resources/Ships/osterbotten/osterbotten_hull.obj
PathnameFull=Resources/Ships/osterbotten/osterbotten.gltf
PathnamePropeller1=Resources/Ships/osterbotten/osterbotten_propeller.gltf
PathnamePropeller2=
PathnameRudder=Resources/Ships/osterbotten/osterbotten_rudder.gltf
PathnameRadar1=Resources/Ships/osterbotten/osterbotten_radar1.gltf
PathnameRadar2=Resources/Ships/osterbotten/osterbotten_radar2.gltf
PathnameFlag=Resources/Ships/osterbotten/Flag_of_the_Isle_of_Mann.png
ThrustSound=Resources/Sounds/Engine18.wav
BowThrusterSound=
SternThrusterSound=
[Views]
ViewWheel=-37.6 15.8 0
ViewLeft=-37.2555 15.8 -6.5
ViewRight=-37.255 15.8 6.5
ViewBow=46.967 8 0
ViewStern=-46.6 13.95 -0.5
[Dimensions]
Class=7
Length=107.33
SpeedMaxKt=14.0
SpeedEcoKt=13.0
Mass_t=7000
PosGravity=0.8 -1.75 0
PitchRollFactor=0.25
EnvMapFactor=0
ContourType=1
AreaWetted=2262.09
LWL=104.26
PositionY=-0.67
AreaFront=182.0126
AreaFrontCenter=0 6.5734 3.0615
AreaLat=900.2948
AreaLatCenter=-4.9508 4.6818 0
[Power]
PosPower=-48 -3 0
PowerkW=8800
PowerStepMax=20
[Propellers]
PropRpmMax=110
PropRpmIncrement=2
nPropeller=1
PosPropeller1=-47.455 -3 0
PropTorque1=1
PosPropeller2=0 0 0
PropTorque2=0
PropDiameter=3.0
WakeWidth=0.7
[Rudder]
PosRudder=-51.255 -2.38 0
RudderIncrement=1
RudderStepMax=35
RudderRotSpeed=5.0
nRudder=1
PosRudder1=-50.582 0.31 0
PosRudder2=0 0 0
[Turning]
TurnabilityAtSpeed=0.2
RoTMax=180
PivotFwd=0.2
PivotBwd=0.7
CentrifugalPerf=1.5
[BowThruster]
HasBowThruster=0
PosBowThruster=0 0 0
BowThrusterPerf=0.4
BowThrusterPowerW=10000
BowThrusterStepMax=5
BowThrusterRpmMin=0
BowThrusterRpmMax=500
BowThrusterRpmIncrement=10
[SternThruster]
HasSternThruster=0
PosSternThruster=0 0 0
SternThrusterPerf=0.4
SternThrusterPowerW=10000
SternThrusterStepMax=5
SternThrusterRpmMin=0
SternThrusterRpmMax=500
SternThrusterRpmIncrement=10
[Autopilot]
BaseP=2
BaseI=1
BaseD=30
MaxIntegral=2
[Radar]
nRadar=2
PosRadar1=-40.955 21.2 0
RotationRadar1=30
PosRadar2=-40.955 19.75 0
RotationRadar2=20
[Flag]
bFlag=1
PosFlag=-46.859 15.174 0.23174
DimXFlag=1.5
[Spray]
SprayVerticalPerf=20
SprayMultiplier=5
SprayLength=0.1
SprayType=1
[Chimneys]
nChimney=1
PosChimney1=-45.4 19.137 0
PosChimney2=0 0 0
[Lights]
LightPositions=-36.9552 14.45 -7.45,-36.9552 14.45 7.45,-52.555 6 0,-42.155 22.7 0,45.721 18.587 0
LightColors=1 0 0,0 1 0,1 1 1,1 1 1,1 1 1
[Waves]
CenterFore=105
BaseFroude=10