;gaist-ultra-V7_1, AI_Fehn_Light, Henrik_Nielsen
[Files]
ShortName=Cargo Ocean Trader
PathnameHull=Resources/Ships/ocean_trader/ocean_trader_hull.obj
PathnameFull=Resources/Ships/ocean_trader/ocean_trader.gltf
PathnamePropeller1=Resources/Ships/ocean_trader/ocean_trader_propeller.gltf
PathnamePropeller2=
PathnameRudder=Resources/Ships/ocean_trader/ocean_trader_rudder.gltf
PathnameRadar1=Resources/Ships/ocean_trader/ocean_trader_radar1.gltf
PathnameRadar2=Resources/Ships/ocean_trader/ocean_trader_radar2.gltf
PathnameFlag=Resources/Ships/ocean_trader/Flag_of_Madeira.png
ThrustSound=Resources/Sounds/Engine18.wav
BowThrusterSound=
SternThrusterSound=
[Views]
ViewWheel=-37 17 0
ViewLeft=-36.896 17 -9.5
ViewRight=-36.896 17 9.5
ViewBow=44.385 12 1
ViewStern=-53.091 8.6 -0.97
[Dimensions]
Class=7
Length=107.54
SpeedMaxKt=15
SpeedEcoKt=13.9
Mass_t=10500
PosGravity=-1.2 -1.5 0
PitchRollFactor=0.25
EnvMapFactor=0
ContourType=1
AreaWetted=2877.76
LWL=107.01
PositionY=-1.01
AreaFront=246.2140
AreaFrontCenter=0 6.7161 3.5269
AreaLat=1680.1268
AreaLatCenter=-4.2993 8.2032 0
[Power]
PosPower=-49 -3.96 0
PowerkW=15000
PowerStepMax=20
[Propellers]
PropRpmMax=110
PropRpmIncrement=2
nPropeller=1
PosPropeller1=-48.462 -3.9576 0
PropTorque1=1
PosPropeller2=0 0 0
PropTorque2=0
PropDiameter=4.0
WakeWidth=0.7
[Rudder]
PosRudder=-51.7 -3.42 0
RudderIncrement=1
RudderStepMax=35
RudderRotSpeed=5.0
nRudder=1
PosRudder1=-51.169 -0.878 0
PosRudder2=0 0 0
[Turning]
TurnabilityAtSpeed=0.2
RoTMax=180
PivotFwd=0.2
PivotBwd=0.7
CentrifugalPerf=1.5
[BowThruster]
HasBowThruster=0
PosBowThruster=0 0 0
BowThrusterPerf=0.4
BowThrusterPowerW=10000
BowThrusterStepMax=5
BowThrusterRpmMin=0
BowThrusterRpmMax=500
BowThrusterRpmIncrement=10
[SternThruster]
HasSternThruster=0
PosSternThruster=0 0 0
SternThrusterPerf=0.4
SternThrusterPowerW=10000
SternThrusterStepMax=5
SternThrusterRpmMin=0
SternThrusterRpmMax=500
SternThrusterRpmIncrement=10
[Autopilot]
BaseP=2
BaseI=1
BaseD=30
MaxIntegral=2
[Radar]
nRadar=2
PosRadar1=-41.532 24.3 0
RotationRadar1=30
PosRadar2=-40.526 22.2 -2.7
RotationRadar2=20
[Flag]
bFlag=1
PosFlag=-53.417 15.316 -2.99
DimXFlag=1.5
[Spray]
SprayVerticalPerf=20
SprayMultiplier=5
SprayLength=0.1
SprayType=1
[Chimneys]
nChimney=1
PosChimney1=-47.467 20.067 -0.4
PosChimney2=0 0 0
[Lights]
LightPositions=-35.797 10.259 -9.15,-35.797 10.259 9.15,-53.489 7.2 0,-42.838 26.765 0,45.165 15.847 0
LightColors=1 0 0,0 1 0,1 1 1,1 1 1,1 1 1
[Waves]
CenterFore=105
BaseFroude=10