;gaist-ultra-V7_1, AI_MV_Mar, Henrik_Nielsen
[Files]
ShortName=Cargo Mar
PathnameHull=Resources/Ships/mar/mar_hull.obj
PathnameFull=Resources/Ships/mar/mar.gltf
PathnamePropeller1=Resources/Ships/mar/mar_propeller.gltf
PathnamePropeller2=
PathnameRudder=Resources/Ships/mar/mar_rudder.gltf
PathnameRadar1=Resources/Ships/mar/mar_radar1.gltf
PathnameRadar2=Resources/Ships/mar/mar_radar2.gltf
PathnameFlag=Resources/Ships/mar/Flag_of_Antigua_and_Barbuda.png
ThrustSound=Resources/Sounds/Engine18.wav
BowThrusterSound=
SternThrusterSound=
[Views]
ViewWheel=-39.7 12.6 0
ViewLeft=-40.104 12.6 -8.3
ViewRight=-40.104 12.6 8.3s
ViewBow=57.946 9.15 0
ViewStern=-59.421 7.425 0
[Dimensions]
Class=7
Length=120
SpeedMaxKt=13.6
SpeedEcoKt=12.7
Mass_t=8300
PosGravity=-0.8 -0.5 0
PitchRollFactor=0.25
EnvMapFactor=0
ContourType=1
AreaWetted=2626.02
LWL=116.60
PositionY=0.59
AreaFront=169.5612
AreaFrontCenter=0 5.1094 4.4814
AreaLat=1246.5396
AreaLatCenter=-9.7231 7.2334 0
[Power]
PosPower=-56.667 -3.5953 0
PowerkW=8000
PowerStepMax=20
[Propellers]
PropRpmMax=150
PropRpmIncrement=3
nPropeller=1
PosPropeller1=-56.004 -3.5953 0
PropTorque1=1
PosPropeller2=0 0 0
PropTorque2=0
PropDiameter=3.0
WakeWidth=0.7
[Rudder]
PosRudder=-59.4 -3.15 0
RudderIncrement=1
RudderStepMax=35
RudderRotSpeed=5.0
nRudder=1
PosRudder1=-58.304 -0.8	 0
PosRudder2=0 0 0
[Turning]
TurnabilityAtSpeed=0.28
RoTMax=120
PivotFwd=0.2
PivotBwd=0.7
CentrifugalPerf=1.5
[BowThruster]
HasBowThruster=0
PosBowThruster=0 0 0
BowThrusterPerf=0
BowThrusterPowerW=0
BowThrusterStepMax=0
BowThrusterRpmMin=0
BowThrusterRpmMax=0
BowThrusterRpmIncrement=0
[SternThruster]
HasSternThruster=0
PosSternThruster=0 0 0
SternThrusterPerf=0
SternThrusterPowerW=10000
SternThrusterStepMax=5
SternThrusterRpmMin=0
SternThrusterRpmMax=500
SternThrusterRpmIncrement=10
[Autopilot]
BaseP=2
BaseI=1
BaseD=30
MaxIntegral=2
[Radar]
nRadar=2
PosRadar1=-44.004 22.45 0
RotationRadar1=23
PosRadar2=-44.004 220.35 0
RotationRadar2=17
[Flag]
bFlag=1
PosFlag=-55.89 11.975 0
DimXFlag=1.5
[Spray]
SprayVerticalPerf=20
SprayMultiplier=5
SprayLength=0.1
SprayType=1
[Chimneys]
nChimney=2
PosChimney1=-50.604 17.184 -0.6
PosChimney2=-50.604 17.184 0.6
[Lights]
LightPositions=-39.591 11.35 -8.265,-39.591 11.35 8.265,-56.284 8.7 0,-46.267 24.85 0,47.926 15 0
LightColors=1 0 0,0 1 0,1 1 1,1 1 1,1 1 1
[Waves]
CenterFore=105
BaseFroude=10