;gaist-ultra-V7_1, AI_Annabella, Henrik_Nielsen
[Files]
ShortName=Cargo Elbstrand
PathnameHull=Resources/Ships/elbstrand/elbstrand_hull.obj
PathnameFull=Resources/Ships/elbstrand/elbstrand.gltf
PathnamePropeller1=Resources/Ships/elbstrand/elbstrand_propeller.gltf
PathnamePropeller2=
PathnameRudder=Resources/Ships/elbstrand/elbstrand_rudder.gltf
PathnameRadar1=Resources/Ships/elbstrand/elbstrand_radar1.gltf
PathnameRadar2=Resources/Ships/elbstrand/elbstrand_radar2.gltf
PathnameFlag=Resources/Ships/elbstrand/Flag_of_Antigua_and_Barbuda.png
ThrustSound=Resources/Sounds/Engine18.wav
BowThrusterSound=Resources/Sounds/Engine0.wav
SternThrusterSound=
[Views]
ViewWheel=-54.33 23.7 0
ViewLeft=-55.55 23.7 -10.854
ViewRight=-55.55 23.7 10.854
ViewBow=59.333 13.7 2
ViewStern=-62.1 23.7 1
[Dimensions]
Class=7
Length=134.80
SpeedMaxKt=21.0
SpeedEcoKt=18.3
Mass_t=16500
PosGravity=0 -2 0
PitchRollFactor=0.25
EnvMapFactor=0
ContourType=1
AreaWetted=3956.10
LWL=133.55
PositionY=-0.42
AreaFront=374.8112
AreaFrontCenter=0 9.3477 5.0491
AreaLat=2291.0056
AreaLatCenter=-4.9859 8.7537 0
[Power]
PosPower=-59 -4.85 0
PowerkW=56800
PowerStepMax=20
[Propellers]
PropRpmMax=110	
PropRpmIncrement=2
nPropeller=1
PosPropeller1=-58.6 -4.8286 0
PropTorque1=1
PosPropeller2=0 0 0
PropTorque2=0
PropDiameter=4.03
WakeWidth=0.7
[Rudder]
PosRudder=-63.495 -3.73 0
RudderIncrement=1
RudderStepMax=35
RudderRotSpeed=3
nRudder=1
PosRudder1=-62.414 -0.115 0
PosRudder2=0 0 0
[Turning]
TurnabilityAtSpeed=0.3
RoTMax=120
PivotFwd=0.2
PivotBwd=0.7
CentrifugalPerf=2
[BowThruster]
HasBowThruster=1
PosBowThruster=49.4 -4.4 0
BowThrusterPerf=8
BowThrusterPowerW=10000
BowThrusterStepMax=5
BowThrusterRpmMin=0
BowThrusterRpmMax=500
BowThrusterRpmIncrement=100
[SternThruster]
HasSternThruster=0
PosSternThruster=0 0 0
SternThrusterPerf=0.4
SternThrusterPowerW=10000
SternThrusterStepMax=5
SternThrusterRpmMin=0
SternThrusterRpmMax=500
SternThrusterRpmIncrement=10
[Autopilot]
BaseP=2
BaseI=1
BaseD=30
MaxIntegral=2
[Radar]
nRadar=2
PosRadar1=-56.2 30.6 4.3
RotationRadar1=23
PosRadar2=-56.2 29.9 -4.3
RotationRadar2=19
[Flag]
bFlag=1
PosFlag=-62.57 25.382 0
DimXFlag=1.5
[Spray]
SprayVerticalPerf=20
SprayMultiplier=5
SprayLength=0.1
SprayType=1
[Chimneys]
nChimney=1
PosChimney1=-61.829 28.758 -6.7
PosChimney2=0 0 0
[Lights]
LightPositions=24.3 12.15 -11.25,24.3 12.15 11.25,-66.847 10.3 0,-59 33.1 0,60.84 19.15 0
LightColors=1 0 0,0 1 0,1 1 1,1 1 1,1 1 1
[Waves]
CenterFore=80
BaseFroude=10