;gaist-ultra-V7_1, AI_Grande_Anversa, Henrik_Nielsen
[Files]
ShortName=Cargo Grande Anversa
PathnameHull=Resources/Ships/grande_anversa/grande_anversa_hull.obj
PathnameFull=Resources/Ships/grande_anversa/grande_anversa.gltf
PathnamePropeller1=Resources/Ships/grande_anversa/grande_anversa_propeller.gltf
PathnamePropeller2=
PathnameRudder=Resources/Ships/grande_anversa/grande_anversa_rudder.gltf
PathnameRadar1=Resources/Ships/grande_anversa/grande_anversa_radar1.gltf
PathnameRadar2=Resources/Ships/grande_anversa/grande_anversa_radar2.gltf
PathnameFlag=Resources/Ships/grande_anversa/Flag_of_Italy.png
ThrustSound=Resources/Sounds/Engine18.wav
BowThrusterSound=
SternThrusterSound=
[Views]
ViewWheel=67.164 24.5 0
ViewLeft=65.214 24.5 -15.501
ViewRight=65.214 24.5 15.501
ViewBow=88.357 21.5 0
ViewStern=-86.3232 21.5 -3
[Dimensions]
Class=7
Length=176.10
SpeedMaxKt=19.2
SpeedEcoKt=17.7
Mass_t=24000
PosGravity=0 -2 0
PitchRollFactor=0.25
EnvMapFactor=0
ContourType=1
AreaWetted=5634.04
LWL=176
PositionY=0.05
AreaFront=541.7983
AreaFrontCenter=0 11.1553 7.4138
AreaLat=4253.9644
AreaLatCenter=0.4647 12.3792 0
[Power]
PosPower=-77.4 -4.5 0
PowerkW=60000
PowerStepMax=20
[Propellers]
PropRpmMax=120	
PropRpmIncrement=4
nPropeller=1
PosPropeller1=-76.886 -4.5 0
PropTorque1=1
PosPropeller2=0 0 0
PropTorque2=0
PropDiameter=4.76
WakeWidth=0.8
[Rudder]
PosRudder=-95.438 -3.95 0
RudderIncrement=1
RudderStepMax=35
RudderRotSpeed=1.6
nRudder=1
PosRudder1=-81.559 -0.31198 0
PosRudder2=0 0 0
[Turning]
TurnabilityAtSpeed=0.33
RoTMax=100
PivotFwd=0.2
PivotBwd=0.7
CentrifugalPerf=1.5
[BowThruster]
HasBowThruster=0
PosBowThruster=0 0 0
BowThrusterPerf=0.4
BowThrusterPowerW=10000
BowThrusterStepMax=5
BowThrusterRpmMin=0
BowThrusterRpmMax=500
BowThrusterRpmIncrement=10
[SternThruster]
HasSternThruster=0
PosSternThruster=0 0 0
SternThrusterPerf=0.4
SternThrusterPowerW=10000
SternThrusterStepMax=5
SternThrusterRpmMin=0
SternThrusterRpmMax=500
SternThrusterRpmIncrement=10
[Autopilot]
BaseP=2
BaseI=1
BaseD=30
MaxIntegral=2
[Radar]
nRadar=2
PosRadar1=60.614 30.9 2.4989
RotationRadar1=21
PosRadar2=60.614 29.9 -2.5011
RotationRadar2=20
[Flag]
bFlag=1
PosFlag=-86.669 22.982 1.9989
DimXFlag=2
[Spray]
SprayVerticalPerf=20
SprayMultiplier=10
SprayLength=0.05
SprayType=1
[Chimneys]
nChimney=1
PosChimney1=-48.286 32.2 3.9989
PosChimney2=-48.286 32.2 3.9989
[Lights]
LightPositions=67.171 23.543 -15.358,67.171 23.543 15.358,-86.666 22.995 -0.001,-2.8057 33.7 -0.001,88.894 28.21 -0.001
LightColors=1 0 0,0 1 0,1 1 1,1 1 1,1 1 1
[Waves]
CenterFore=130
BaseFroude=10