;gaist-ultra-V7_1, AI_Angela, Henrik_Nielsen
[Files]
ShortName=Cargo Angela
PathnameHull=Resources/Ships/angela/angela_hull.obj
PathnameFull=Resources/Ships/angela/angela.gltf
PathnamePropeller1=Resources/Ships/angela/angela_propeller.gltf
PathnamePropeller2=
PathnameRudder=Resources/Ships/angela/angela_rudder.gltf
PathnameRadar1=Resources/Ships/angela/angela_radar1.gltf
PathnameRadar2=Resources/Ships/angela/angela_radar2.gltf
PathnameFlag=Resources/Ships/angela/Flag_of_Panama.png
ThrustSound=Resources/Sounds/Engine18.wav
BowThrusterSound=
SternThrusterSound=
[Views]
ViewWheel=-71 21.5 0
ViewLeft=-71.354 21.5 -15.1
ViewRight=-71.354 21.5 15.1
ViewBow=84.055 10.9 3.4
ViewStern=-92.932 10 0
[Dimensions]
Class=7
Length=189.60
SpeedMaxKt=15.6
SpeedEcoKt=13.9
Mass_t=52000
PosGravity=0 -3 0
PitchRollFactor=0.25
EnvMapFactor=0
ContourType=1
AreaWetted=8793.62
LWL=189.10
PositionY=-0.07
AreaFront=516.3884
AreaFrontCenter=0 6.6054 7.3446
AreaLat=3333.3154
AreaLatCenter=-6.5528 10.1519 0
[Power]
PosPower=-90.6 -6.6546 0
PowerkW=9000
PowerStepMax=20
[Propellers]
PropRpmMax=87	
PropRpmIncrement=1.8
nPropeller=1
PosPropeller1=-90 -6.6546 0
PropTorque1=-1
PosPropeller2=0 0 0
PropTorque2=0
PropDiameter=7.46
WakeWidth=0.5
[Rudder]
PosRudder=-95.438 -3.95 0
RudderIncrement=1
RudderStepMax=35
RudderRotSpeed=1.6
nRudder=1
PosRudder1=-93.771 -0.7 0
PosRudder2=0 0 0
[Turning]
TurnabilityAtSpeed=0.3
RoTMax=70
PivotFwd=0.2
PivotBwd=0.7
CentrifugalPerf=1.5
[BowThruster]
HasBowThruster=0
PosBowThruster=0 0 0
BowThrusterPerf=0.4
BowThrusterPowerW=10000
BowThrusterStepMax=5
BowThrusterRpmMin=0
BowThrusterRpmMax=500
BowThrusterRpmIncrement=10
[SternThruster]
HasSternThruster=0
PosSternThruster=0 0 0
SternThrusterPerf=0.4
SternThrusterPowerW=10000
SternThrusterStepMax=5
SternThrusterRpmMin=0
SternThrusterRpmMax=500
SternThrusterRpmIncrement=10
[Autopilot]
BaseP=2
BaseI=1
BaseD=30
MaxIntegral=2
[Radar]
nRadar=2
PosRadar1=-74.504 33 0
RotationRadar1=21
PosRadar2=-74.504 30.145 0
RotationRadar2=20
[Flag]
bFlag=1
PosFlag=-97.774 11.045 0
DimXFlag=2
[Spray]
SprayVerticalPerf=20
SprayMultiplier=10
SprayLength=0.05
SprayType=1
[Chimneys]
nChimney=1
PosChimney1=-86.25 29.482 0
PosChimney2=-86.25 29.482 0
[Lights]
LightPositions=-70.451 13.845 -15.928,-70.451 13.845 15.928,-97.774 11.045 0,-78.424 36.489 0,86.646 21.945 0
LightColors=1 0 0,0 1 0,1 1 1,1 1 1,1 1 1
[Waves]
CenterFore=150
BaseFroude=10