;gaist-ultra-V7_1, AI_Global_Vision, Henrik_Nielsen
[Files]
ShortName=Cargo Global Vision
PathnameHull=Resources/Ships/global_vision/global_vision_hull.obj
PathnameFull=Resources/Ships/global_vision/global_vision.gltf
PathnamePropeller1=Resources/Ships/global_vision/global_vision_propeller.gltf
PathnamePropeller2=
PathnameRudder=Resources/Ships/global_vision/global_vision_rudder.gltf
PathnameRadar1=Resources/Ships/global_vision/global_vision_radar1.gltf
PathnameRadar2=Resources/Ships/global_vision/global_vision_radar2.gltf
PathnameFlag=Resources/Ships/global_vision/Flag_of_Panama.png
ThrustSound=Resources/Sounds/Engine18.wav
BowThrusterSound=
SternThrusterSound=
[Views]
ViewWheel=-69.6 24.9 0
ViewLeft=-72.452 24.9 -16.1
ViewRight=-72.452 24.9 16.1
ViewBow=88.548 14 0
ViewStern=-95.452 10.4 -4
[Dimensions]
Class=7
Length=189.61
SpeedMaxKt=15.5
SpeedEcoKt=13.8
Mass_t=59000
PosGravity=0 -3 0
PitchRollFactor=0.25
EnvMapFactor=0
ContourType=1
AreaWetted=9010.08
LWL=188.20
PositionY=0
AreaFront=574.0906
AreaFrontCenter=0 7.1711 7.2548
AreaLat=3373.0979
AreaLatCenter=-9.7540 10.4553 0
[Power]
PosPower=-91 -8.06 0
PowerkW=9000
PowerStepMax=20
[Propellers]
PropRpmMax=87	
PropRpmIncrement=1.8
nPropeller=1
PosPropeller1=-90.7 -8.06 0
PropTorque1=-1
PosPropeller2=0 0 0
PropTorque2=0
PropDiameter=7.46
WakeWidth=0.5
[Rudder]
PosRudder=-96 -6.56 0
RudderIncrement=1
RudderStepMax=35
RudderRotSpeed=1.6
nRudder=1
PosRudder1=-94.102 -0.06 0
PosRudder2=0 0 0
[Turning]
TurnabilityAtSpeed=0.3
RoTMax=50
PivotFwd=0.2
PivotBwd=0.7
CentrifugalPerf=1.5
[BowThruster]
HasBowThruster=0
PosBowThruster=0 0 0
BowThrusterPerf=0.4
BowThrusterPowerW=10000
BowThrusterStepMax=5
BowThrusterRpmMin=0
BowThrusterRpmMax=500
BowThrusterRpmIncrement=10
[SternThruster]
HasSternThruster=0
PosSternThruster=0 0 0
SternThrusterPerf=0.4
SternThrusterPowerW=10000
SternThrusterStepMax=5
SternThrusterRpmMin=0
SternThrusterRpmMax=500
SternThrusterRpmIncrement=10
[Autopilot]
BaseP=2
BaseI=1
BaseD=30
MaxIntegral=2
[Radar]
nRadar=2
PosRadar1=-73.552 35.64 0
RotationRadar1=21
PosRadar2=-73.552 32.94 0
RotationRadar2=20
[Flag]
bFlag=1
PosFlag=-98.371 12.994 2.403
DimXFlag=2
[Spray]
SprayVerticalPerf=20
SprayMultiplier=10
SprayLength=0.05
SprayType=1
[Chimneys]
nChimney=1
PosChimney1=-86.726 32.513 0
PosChimney2=-86.726 32.513 0
[Lights]
LightPositions=-71.399 21.69 -16.028,-71.399 21.69 16.028,-98.802 10.62 1.9,-77.471 39.284 0,86.098 25.64 0
LightColors=1 0 0,0 1 0,1 1 1,1 1 1,1 1 1
[Waves]
CenterFore=150
BaseFroude=10