;gaist-ultra-V7_1, AI_Torm_Bulk, Henrik_Nielsen
[Files]
ShortName=Cargo Agri Kinsale
PathnameHull=Resources/Ships/agri_kinsale/agri_kinsale_hull.obj
PathnameFull=Resources/Ships/agri_kinsale/agri_kinsale.gltf
PathnamePropeller1=Resources/Ships/agri_kinsale/agri_kinsale_propeller.gltf
PathnamePropeller2=
PathnameRudder=Resources/Ships/agri_kinsale/agri_kinsale_rudder.gltf
PathnameRadar1=Resources/Ships/agri_kinsale/agri_kinsale_radar1.gltf
PathnameRadar2=Resources/Ships/agri_kinsale/agri_kinsale_radar2.gltf
PathnameFlag=Resources/Ships/agri_kinsale/Flag_of_Panama.png
ThrustSound=Resources/Sounds/Engine18.wav
BowThrusterSound=
SternThrusterSound=
[Views]
ViewWheel=-81.017 22.375 0
ViewLeft=-81.4 22.375 -15.465
ViewRight=-81.4 22.375 15.465
ViewBow=97.447 10.4 0
ViewStern=-106.94 8.57 0
[Dimensions]
Class=8
Length=225.25
SpeedMaxKt=18.9
SpeedEcoKt=16.9
Mass_t=71000
PosGravity=3.2 -3 0
PitchRollFactor=0.25
EnvMapFactor=0
ContourType=1
AreaWetted=10875.59
LWL=221.60
PositionY=1.21
AreaFront=501.7339
AreaFrontCenter=0 4.8480 8.2326
AreaLat=2242.8140
AreaLatCenter=-10.4586 7.4188 0
[Power]
PosPower=-106 -9.125 0
PowerkW=19500
PowerStepMax=20
[Propellers]
PropRpmMax=87
PropRpmIncrement=1.8
nPropeller=1
PosPropeller1=-104.6 -9.125 0
PropTorque1=-1
PosPropeller2=0 0 0
PropTorque2=0
PropDiameter=4.8
WakeWidth=0.5
[Rudder]
PosRudder=-110.51 -6.2395 0
RudderIncrement=1
RudderStepMax=35
RudderRotSpeed=1.6
nRudder=1
PosRudder1=-107.89 -0.76 0
PosRudder2=0 0 0
[Turning]
TurnabilityAtSpeed=0.4
RoTMax=45
PivotFwd=0.2
PivotBwd=0.7
CentrifugalPerf=1.5
[BowThruster]
HasBowThruster=0
PosBowThruster=0 0 0
BowThrusterPerf=0.4
BowThrusterPowerW=10000
BowThrusterStepMax=5
BowThrusterRpmMin=0
BowThrusterRpmMax=500
BowThrusterRpmIncrement=10
[SternThruster]
HasSternThruster=0
PosSternThruster=0 0 0
SternThrusterPerf=0.4
SternThrusterPowerW=10000
SternThrusterStepMax=5
SternThrusterRpmMin=0
SternThrusterRpmMax=500
SternThrusterRpmIncrement=10
[Autopilot]
BaseP=2
BaseI=1
BaseD=30
MaxIntegral=2
[Radar]
nRadar=2
PosRadar1=-84.6 33.069 0
RotationRadar1=21
PosRadar2=-84.6 30.175 0
RotationRadar2=20
[Flag]
bFlag=1
PosFlag=-112.56 10.053 1.2318
DimXFlag=2
[Spray]
SprayVerticalPerf=20
SprayMultiplier=10
SprayLength=0.05
SprayType=1
[Chimneys]
nChimney=2
PosChimney1=-98.011 29.748 -0.16
PosChimney2=-98.011 29.748 0.16
[Lights]
LightPositions=-80.7 11.375 -15.95,-80.7 11.375 15.95,-112.85 9.7551 0,-88.645 36.645 0,103.6 21.525 -0.05
LightColors=1 0 0,0 1 0,1 1 1,1 1 1,1 1 1
[Waves]
CenterFore=180
BaseFroude=10