;gaist-ultra-V7_1, AI_Type_45_Destroyer, Henrik_Nielsen
[Files]
ShortName=HMS Duncan
PathnameHull=Resources/Ships/hms_duncan/hms_duncan_hull.obj
PathnameFull=Resources/Ships/hms_duncan/hms_duncan.gltf
PathnamePropeller1=Resources/Ships/hms_duncan/hms_duncan_propeller1.gltf
PathnamePropeller2=Resources/Ships/hms_duncan/hms_duncan_propeller2.gltf
PathnameRudder=Resources/Ships/hms_duncan/hms_duncan_rudder.gltf
PathnameRadar1=Resources/Ships/hms_duncan/hms_duncan_radar1.gltf
PathnameRadar2=Resources/Ships/hms_duncan/hms_duncan_radar2.gltf
PathnameFlag=Resources/Ships/hms_duncan/Naval_ensign_of_the_United_Kingdom.png
ThrustSound=Resources/Sounds/Engine16.wav
BowThrusterSound=
SternThrusterSound=
[Views]
ViewWheel=24.5 15.686 0.00757
ViewLeft=22.9 15.686 -9
ViewRight=22.9 15.686 9
ViewBow=38.3 11 0
ViewStern=-51.467 9.355 -0.087009 
[Dimensions]
Class=2
Length=153.44
SpeedMaxKt=29.9
SpeedEcoKt=27.0
Mass_t=7500
PosGravity=2.6 -2.3 0
PitchRollFactor=0.25
EnvMapFactor=0
ContourType=1
AreaWetted=2791.72
LWL=143.35
PositionY=0.33
AreaFront=279.0889
AreaFrontCenter=0 11.4777 4.1284
AreaLat=2102.7673
AreaLatCenter=-0.5705 9.2508 0
[Power]
PosPower=-65.5 -4 0
PowerkW=89000
PowerStepMax=20
[Propellers]
PropRpmMax=250
PropRpmIncrement=12
nPropeller=2
PosPropeller1=-65.499 -4.0667 -4
PropTorque1=-1
PosPropeller2=-65.499 -4.667 4
PropTorque2=1
PropDiameter=3.89
WakeWidth=0.7
[Rudder]
PosRudder=-70.522 -3.1534 0
RudderIncrement=1
RudderStepMax=35
RudderRotSpeed=2
nRudder=2
PosRudder1=-69.5 -0.64358 4
PosRudder2=-69.5 -0.64358 -4
[Turning]
TurnabilityAtSpeed=0.3
RoTMax=150
PivotFwd=0.3
PivotBwd=0.7
CentrifugalPerf=3
[BowThruster]
HasBowThruster=0
PosBowThruster=0 0 0
BowThrusterPerf=0.4
BowThrusterPowerW=10000
BowThrusterStepMax=5
BowThrusterRpmMin=0
BowThrusterRpmMax=500
BowThrusterRpmIncrement=10
[SternThruster]
HasSternThruster=0
PosSternThruster=0 0 0
SternThrusterPerf=0.4
SternThrusterPowerW=10000
SternThrusterStepMax=5
SternThrusterRpmMin=0
SternThrusterRpmMax=500
SternThrusterRpmIncrement=10
[Autopilot]
BaseP=5
BaseI=2
BaseD=30
MaxIntegral=5
[Radar]
nRadar=2
PosRadar1=-28.5 24.5 0
RotationRadar1=40
PosRadar2=22 19.4 -5.1
RotationRadar2=20
[Flag]
bFlag=1
PosFlag=16.3 21.6 6
DimXFlag=2.5
[Spray]
SprayVerticalPerf=20
SprayMultiplier=5
SprayLength=0.1
SprayType=0
[Chimneys]
nChimney=2
PosChimney1=-0.6 20.2 0
PosChimney2=-33.8 19.5 0
[Lights]
LightPositions=18.1 21.25 -4.2,18.1 21.25 4.2,-76.16 7.82 0,-15.7 40.3 0,22.8 22.3 0
LightColors=1 0 0,0 1 0,1 1 1,1 1 1,1 1 1
[Waves]
CenterFore=50
BaseFroude=10