;gaist-ultra-V7_1, AI_Nis_Randers, Henrik_Nielsen
[Files]
ShortName=SAR Nis Randers
PathnameHull=Resources/Ships/nis_randers/nis_randers_hull.obj
PathnameFull=Resources/Ships/nis_randers/nis_randers.gltf
PathnamePropeller1=Resources/Ships/nis_randers/nis_randers_propeller1.gltf
PathnamePropeller2=Resources/Ships/nis_randers/nis_randers_propeller2.gltf
PathnameRudder=Resources/Ships/nis_randers/nis_randers_rudder.gltf
PathnameRadar1=Resources/Ships/nis_randers/nis_randers_radar1.gltf
PathnameRadar2=Resources/Ships/nis_randers/nis_randers_radar2.gltf
PathnameFlag=Resources/Ships/nis_randers/Flag_of_Germany.png
ThrustSound=Resources/Sounds/Engine16.wav
BowThrusterSound=
SternThrusterSound=
[Views]
ViewWheel=4.1 5.7 0.8
ViewLeft=4.1 5.7 -2.517
ViewRight=4.1 5.7 2.517
ViewBow=13 4.5 0
ViewStern=-2 3.2 2.5
[Dimensions]
Class=5
Length=28
SpeedMaxKt=25.9
SpeedEcoKt=22.9
Mass_t=140
PosGravity=0 -0.5 0
PitchRollFactor=0.3
EnvMapFactor=0
ContourType=1
AreaWetted=189.50
LWL=26.15
PositionY=-0.02
AreaFront=27.7598
AreaFrontCenter=0 3.3910 1.3052
AreaLat=136.9196
AreaLatCenter=1.9593 3.0270 0
[Power]
PosPower=-10.2 -1.15 0
PowerkW=1000
PowerStepMax=20
[Propellers]
PropRpmMax=500
PropRpmIncrement=150
nPropeller=2
PosPropeller1=-10.024 -1.1495 -1
PropTorque1=1
PosPropeller2=-10.024 -1.1495 1
PropTorque2=-1
PropDiameter=1.02
WakeWidth=1
[Rudder]
PosRudder=-18.8 -1.63 0
RudderIncrement=1
RudderStepMax=35
RudderRotSpeed=17
nRudder=2
PosRudder1=-10.833 -0.2 -1
PosRudder2=-10.833 -0.2 1
[Turning]
TurnabilityAtSpeed=1
RoTMax=360
PivotFwd=0.25
PivotBwd=0.65
CentrifugalPerf=3
[Spray]
SprayVerticalPerf=5
SprayMultiplier=10
SprayLength=0.15
SprayType=0
[Chimneys]
nChimney=2
PosChimney1=-12.05 0.85 -2.45
PosChimney2=-12.05 0.85 2.45
[BowThruster]
HasBowThruster=0
PosBowThruster=0 0 0
BowThrusterPerf=0
BowThrusterPowerW=0
BowThrusterStepMax=0
BowThrusterRpmMin=0
BowThrusterRpmMax=500
BowThrusterRpmIncrement=0
[SternThruster]
HasSternThruster=0
PosSternThruster=0 0 0
SternThrusterPerf=0
SternThrusterPowerW=0
SternThrusterStepMax=0
SternThrusterRpmMin=0
SternThrusterRpmMax=0
SternThrusterRpmIncrement=0
[Autopilot]
BaseP=2
BaseI=1
BaseD=30
MaxIntegral=2
[Lights]
LightPositions=3.7207 6.9 -2.3207,3.7207 6.9 2.3207,-1.55 4.99 0,0.7 11.475 0
LightColors=1 0 0,0 1 0,1 1 1,1 1 1
[Radar]
nRadar=2
PosRadar1=0.66392 10.771 0.014215
RotationRadar1=20
PosRadar2=1.1 9.16 0
RotationRadar2=30
[Waves]
CenterFore=20
BaseFroude=0
[Flag]
bFlag=1
PosFlag=-0.71563 11.174 0.73909
DimXFlag=1
