;gaist-ultra-V7_1, AI_Itasca, Henrik_Nielsen
[Files]
ShortName=Fishing Vessel Itasca
PathnameHull=Resources/Ships/itasca/itasca_hull.obj
PathnameFull=Resources/Ships/itasca/itasca.gltf
PathnamePropeller1=Resources/Ships/itasca/itasca_propeller.gltf
PathnamePropeller2=
PathnameRudder=Resources/Ships/itasca/itasca_rudder.gltf
PathnameRadar1=
PathnameRadar2=
PathnameFlag=Resources/Ships/itasca/Flag_of_France.png
ThrustSound=Resources/Sounds/Engine10.wav
BowThrusterSound=
SternThrusterSound=
[Views]
ViewWheel=-0.41 4.75 0
ViewLeft=-1.4393 4.75 -2.25
ViewRight=-1.4393 4.75 2.25
ViewBow=6.1291 4.7 0
ViewStern=-10.38 2.5 1.78
[Dimensions]
Class=3
Length=25.76
SpeedMaxKt=10.8
SpeedEcoKt=10.1
Mass_t=200
PosGravity=-0.8 -0.5 0
PitchRollFactor=1.5
EnvMapFactor=0
ContourType=2
AreaWetted=197.84
LWL=22.93
PositionY=0.26
AreaFront=27.9102
AreaFrontCenter=0 2.1657 1.8361
AreaLat=109.7821
AreaLatCenter=-0.4015 2.6483 0
[Power]
PosPower=-10.156 -1.93 0
PowerkW=400
PowerStepMax=20
[Propellers]
PropRpmMax=400
PropRpmIncrement=20
nPropeller=1
PosPropeller1=-9.8339 -1.9305 0
PropTorque1=1
PosPropeller2=0 0 0
PropTorque2=0
PropDiameter=1.23
WakeWidth=1.1
[Rudder]
PosRudder=-12.11 -1.65 0
RudderIncrement=1
RudderStepMax=45
RudderRotSpeed=10
nRudder=1
PosRudder1=-11.938 -0.28 0
PosRudder2=0 0 0
[Turning]
TurnabilityAtSpeed=1
RoTMax=360
PivotFwd=0.4
PivotBwd=0.6
CentrifugalPerf=0.5
[BowThruster]
HasBowThruster=0
PosBowThruster=0 0 0
BowThrusterPerf=0.4
BowThrusterPowerW=10000
BowThrusterStepMax=5
BowThrusterRpmMin=0
BowThrusterRpmMax=500
BowThrusterRpmIncrement=100
[SternThruster]
HasSternThruster=0
PosSternThruster=0 0 0
SternThrusterPerf=0.4
SternThrusterPowerW=10000
SternThrusterStepMax=5
SternThrusterRpmMin=0
SternThrusterRpmMax=500
SternThrusterRpmIncrement=10
[Autopilot]
BaseP=3
BaseI=2
BaseD=30
MaxIntegral=4
[Radar]
nRadar=0
PosRadar1=0 0 0
RotationRadar1=20
PosRadar2=0 0 0
RotationRadar2=40
[Flag]
bFlag=1
PosFlag=-4.74 9.65 0
DimXFlag=0.6
[Spray]
SprayVerticalPerf=2
SprayMultiplier=10
SprayLength=0.1
SprayType=0
[Chimneys]
nChimney=1
PosChimney1=-5.4625 6.4123 1.2554
PosChimney2=0 0 0
[Lights]
LightPositions=-4.4444 4.6695 -2.91,-4.4444 4.6695 2.91,-11.489 6 0,-4.5393 9.2 0.59849,-4.4393 7.8 0.59849
LightColors=1 0 0,0 1 0,1 1 1,1 0 0,1 1 1
[Waves]
CenterFore=40
BaseFroude=10