;gaist-ultra-V7_1, AI_Dover_Seaways, Henrik_Nielsen
[Files]
ShortName=Dunkerque Seaways
PathnameHull=Resources/Ships/dunkerque_seaways/dunkerque_seaways_hull.obj
PathnameFull=Resources/Ships/dunkerque_seaways/dunkerque_seaways.gltf
PathnamePropeller1=Resources/Ships/dunkerque_seaways/dunkerque_seaways_propeller1.gltf
PathnamePropeller2=Resources/Ships/dunkerque_seaways/dunkerque_seaways_propeller2.gltf
PathnameRudder=Resources/Ships/dunkerque_seaways/dunkerque_seaways_rudder.gltf
PathnameRadar1=Resources/Ships/dunkerque_seaways/dunkerque_seaways_radar1.gltf
PathnameRadar2=Resources/Ships/dunkerque_seaways/dunkerque_seaways_radar2.gltf
PathnameFlag=Resources/Ships/dunkerque_seaways/Civil_ensign_of_the_United_Kingdom.png
ThrustSound=Resources/Sounds/Engine18.wav
BowThrusterSound=Resources/Sounds/Engine0.wav
SternThrusterSound=
[Views]
ViewWheel=65 27.9 0
ViewLeft=58.797 27.9 -15.85
ViewRight=58.797 27.9 15.85
ViewBow=72.447 13.5 9.2
ViewStern=-63.485 18.9 0
[Dimensions]
Class=5
Length=153.6
SpeedMaxKt=25.0
SpeedEcoKt=23.3
Mass_t=18564
PosGravity=-3.6 -1,5 0
PitchRollFactor=0.25
EnvMapFactor=0
ContourType=1
AreaWetted=5462.97
LWL=186.50
PositionY=0.67
AreaFront=536.554
AreaFrontCenter=0 13.0176 7.4994
AreaLat=4389.4966
AreaLatCenter=0.9579 14.1004 0
[Power]
PosPower=-82 -4.08651 0
PowerkW=99000
PowerStepMax=20
[Propellers]
PropRpmMax=150
PropRpmIncrement=5
nPropeller=2
PosPropeller1=-80.758 -4.0864 -5.6
PropTorque1=-1
PosPropeller2=-80.758 -4.0864 5.6
PropTorque2=1
PropDiameter=6.23
WakeWidth=0.8
[Rudder]
PosRudder=-86.909 -3.5 0
RudderIncrement=1
RudderStepMax=35
RudderRotSpeed=1.8
nRudder=2
PosRudder1=-85.553 -0.5 -5.6
PosRudder2=-85.553 -0.5 5.6
[Turning]
TurnabilityAtSpeed=0.4
RoTMax=120
PivotFwd=0.2
PivotBwd=0.7
CentrifugalPerf=3
[BowThruster]
HasBowThruster=1
PosBowThruster=74.997 -3 0
BowThrusterPerf=50
BowThrusterPowerW=100000
BowThrusterStepMax=5
BowThrusterRpmMin=0
BowThrusterRpmMax=500
BowThrusterRpmIncrement=100
[SternThruster]
HasSternThruster=0
PosSternThruster=0 0 0
SternThrusterPerf=0
SternThrusterPowerW=100000
SternThrusterStepMax=5
SternThrusterRpmMin=0
SternThrusterRpmMax=500
SternThrusterRpmIncrement=10
[Autopilot]
BaseP=2
BaseI=1
BaseD=30
MaxIntegral=2
[Radar]
nRadar=2
PosRadar1=55.447 38 0
RotationRadar1=21
PosRadar2=56.447 35 0
RotationRadar2=20
[Flag]
bFlag=1
PosFlag=49.962 39.789 1.7879
DimXFlag=2
[Spray]
SprayVerticalPerf=20
SprayMultiplier=5
SprayLength=0.1
SprayType=1
[Chimneys]
nChimney=2
PosChimney1=-22.953 38.8 -1
PosChimney2=-22.953 38.8 1
[Lights]
LightPositions=55.497 17.4 -14.1,55.497 17.4 14.1,-95.253 8.7 0,-15.645 37.8 0,65.397 31.12 0
LightColors=1 0 0,0 1 0,1 1 1,1 1 1,1 1 1
[Waves]
CenterFore=80
BaseFroude=10